'use strict';

const HELP_METADATA = {
  '1337': { help: 'Returns 1337-speak of input text', args: 'string' },
  addtopic: { help: 'Add a topic to the random topic list.', args: 'Topic:string' },
  addadmin: { help: 'Add an authenticated account or Discord ID as a bot admin.', args: 'Subject:string' },
  addperm: { help: 'Assign a global bot permission rank.', args: 'Subject:string Rank:string' },
  adddnsbl: { help: 'Add a DNS blocklist service.', args: 'Service:string' },
  alot: { help: 'Enable or disable Alot and LUA corrections for this channel.', args: 'Action:string' },
  announce: { help: 'Manage repeating announcements for this channel.', args: 'SubCommand:string [Params:string]' },
  antispam: { help: 'Enable or disable new-user spam protection for this channel.', args: 'State:string' },
  authed: { help: 'Show your authenticated permission identity.' },
  aliases: { help: 'Get aliases for a command, or find the root command for an alias.', args: 'Command:string' },
  attack: { help: 'Attack someone and deal damage! Each action can also be used as an alias.', args: 'Action:string Target:string [Item:string]' },
  alias: { help: 'Get aliases for a command, or find the root command for an alias.', args: 'Command:string' },
  bap: { help: 'Baps someone harmlessly without doing damage!', args: '[Target:string Item:string]' },
  bf: { help: 'Does brainfuck', args: 'string' },
  blame: { help: 'Project problems onto someone else!', args: 'Nick:string' },
  bonk: { help: 'Hit someone on the head!', args: '[Target:string Item:string]' },
  calendarfacts: { help: 'Calendar facts based on xkcd comic #1930' },
  care: { help: 'Measure care levels' },
  catfact: { help: 'Cat Facts!' },
  changeprefix: { help: 'Change the command prefix for the bot.', args: 'Prefix:string' },
  choose: { help: 'Randomly picks a choice for you.', args: 'string' },
  chnick: { help: 'Change the bot nick.', args: 'Nick:string' },
  checkdnsbl: { help: 'Check an address against tracked DNS blocklists.', args: 'Address:string' },
  claim: { help: 'Link your Discord identity to your authenticated IRC account.', args: '[Code:string]' },
  clearpings: { help: 'Clears your pings from the DB' },
  command: { help: 'Manage dynamic commands.', args: 'SubCommand:string [Params:string]' },
  curseword: { help: 'Holy manbats Batman!' },
  dbversion: { help: 'Get current database version' },
  defend: { help: 'Defend against attacks and things thrown at you.', args: 'Action:string [Item:string]' },
  defenddebug: { help: 'Inspect or process the pending defense queue.', args: '[Action:string]' },
  cycle: { help: 'Cycle the bot out of and back into a channel.', args: '[Channel:string]' },
  dice: { help: 'Rolls dice and solves mathematical expressions using + - * and /. Dice can be expressed as 1d20 or d20 and supports keep-highest/lowest, exploding dice, and success counting.', args: 'Expression:string' },
  drama: { help: 'Generates random drama using Mod Developers, Projects, and other semi random data.' },
  dnsbl: { help: 'Enable or disable DNSBL join checks in this channel.', args: '[State:string]' },
  deltopic: { help: 'Delete a topic by ID.', args: 'TopicID:int' },
  delperm: { help: 'Remove a global bot permission assignment.', args: 'Subject:string [Rank:string]' },
  discovered: { help: 'Shows discovered potions.', args: '[ListAll:bool]' },
  drink: { help: 'Drink a potion with a certain consistency and appearance and something might happen.', args: '[Potion:string]' },
  dyncmd: { help: 'Dynamic command module status and controls.', args: '[Action:string]' },
  eightball: { help: 'Gives vague answers to all questions.', args: '[Question:string]' },
  fact: { help: 'Animal facts!', args: '[Animal:string]' },
  fling: { help: 'Fling something at someone!', args: 'Target:string [Item:string]' },
  flip: { help: 'Flips the text sent.', args: '[string]' },
  garbage: { help: 'It goes in the garbage', args: '[string]' },
  give: { help: 'If the item is found in the inventory it is given to the target.', args: 'Target:string [Item:string]' },
  github: { help: 'Enable or disable GitHub issue and pull-request information for this channel.', args: '[State:string]' },
  greet: { help: 'Send the bot greeting.' },
  hiss: { help: 'Sneks the text', args: 'string' },
  ignore: { help: 'Globally ignore a user.', args: 'Nick:string' },
  ignorelist: { help: 'List globally ignored users.' },
  jiggle: { help: 'Jiggle', args: '[Thing:string Times:int]' },
  isup: { help: 'Checks if a website is up or down.', args: 'URL:string' },
  inventory: { help: 'Interact with the bots inventory', args: 'SubCommand:string [Item:string]' },
  join: { help: 'Join a channel.', args: 'Channel:string [Key:string]' },
  js: { help: 'Run JavaScript in an isolated, resource-limited sandbox.', args: 'Snippet:string' },
  jumble: { help: 'It jumbles things. Try it. You\'ll be hooked.', args: 'string' },
  juggle: { help: 'Juggle with items', args: '[Number:int]' },
  listaliases: { help: 'Get aliases for a command, or list all aliases.', args: '[Command:string]' },
  listadmins: { help: 'List bot administrator identities.' },
  listcommands: { help: 'List commands.' },
  listdnsbl: { help: 'List tracked DNS blocklist services.' },
  listplugins: { help: 'List currently loaded plugins.' },
  listperms: { help: 'List global bot permission assignments.', args: '[Rank:string]' },
  lootbox: { help: 'Get a loot box! What could be inside!', args: '[LootTarget:string]' },
  loadplugin: { help: 'Load a plugin.', args: 'Plugin:string' },
  lookup: { help: 'Returns DNS information', args: 'Address:string [RecordType:string]' },
  makemagic: { help: 'Magic?', args: 'Item:string' },
  lua: { help: 'Run Lua code snippets or a file by providing a URL.', args: 'Snippet:string' },
  me: { help: 'Send an action as the bot.', args: 'Message:string' },
  moo: { help: 'Moos the text', args: '[string]' },
  msp: { help: 'Sends a CTCP Ping and replies with milliseconds.', args: '[Nick:string...]' },
  newtopic: { help: 'Generates a new topic' },
  nicklen: { help: 'Shows the length of a nick.', args: '[Nick:string]' },
  octime: { help: 'Returns the time in GMT' },
  part: { help: 'Leave a channel.', args: '[Channel:string]' },
  pet: { help: 'Give pets! Give hit points!', args: 'Target:string [Item:string]' },
  phraseban: { help: 'Manage phrases that trigger timed bans in this channel.', args: 'SubCommand:string [Value:string]' },
  ping: { help: 'Sends a CTCP Ping to you, or the supplied user, to check latency.', args: '[Nick:string...]' },
  points: { help: 'Check Internet Points for yourself or another user.', args: '[Nick:string]' },
  potion_lookup: { help: 'Looks up potion information.', args: 'Potion:string' },
  potionstats: { help: 'Shows potion discovery statistics.' },
  quote: { help: 'Returns quotes from the quote database. Also has sub-commands: add, del, list.', args: '[string]' },
  quotes: { help: 'Returns quotes from the quote database.', args: '[string]' },
  rainbow: { help: 'Replies with a rainbow version of the supplied text', args: '[string]' },
  rateitem: { help: 'Rates items attack, defense or healing bonuses', args: 'SubCommand:string [Item:string]' },
  ram: { help: 'Show the bot memory usage.' },
  randompotion: { help: 'Get a random potion' },
  raw: { help: 'Send a raw IRC line.', args: 'Line:string' },
  rdns: { help: 'Returns Reverse DNS information', args: 'Address:string' },
  remdnsbl: { help: 'Remove a DNS blocklist service.', args: 'Service:string' },
  reloadplugin: { help: 'Reload a plugin.', args: 'Plugin:string' },
  remind: { help: '\'remindme 1h20m check your food!\' will send a reminder in the channel the command was sent, or PM if you PMed the bot.', args: 'Time:string Message:string' },
  reminders: { help: 'Gives you a list of your next reminders.' },
  remindthem: { help: '\'remindthem gamax92 1h20m check your food!\' will send a reminder to the supplied nick.', args: 'Nick:string Time:string Message:string' },
  resetlua: { help: 'Reset the Lua sandbox state.' },
  resetpotions: { help: 'Reset potion discovery data.' },
  resetpoints: { help: 'Reset a user\'s Internet Points.', args: 'Nick:string' },
  resettonk: { help: 'Reset tonk data/admin tonk controls.' },
  reverse: { help: 'Reverses the supplied text', args: 'string' },
  rot13: { help: 'Applies the ROT13 cipher to the supplied text', args: 'string' },
  rpg: { help: 'Play the optional persistent RPG: explore rooms, fight creatures, gain levels, and collect gold.', args: 'SubCommand:string [Params:string]' },
  say: { help: 'Send a message as the bot.', args: 'Message:string' },
  sed: { help: 'Applies sed-style corrections to recent chat.' },
  seen: { help: 'Tells you the last time a user was active. Active means they sent a message.', args: 'Nick:string' },
  selene: { help: 'Run snippets through Selene. Also supports URLs.', args: 'Snippet:string' },
  sell: { help: 'Returns a sales pitch for the given argument.', args: 'Item:string' },
  shell: { help: 'Be a nuisance with your very own mortar!', args: '[Target1:string Target2:string Target3:string ItemOrPotion:string]' },
  smash: { help: 'If you ever feel the need to let off some steam.' },
  splash: { help: 'Splash some unfortunate bystander with a potion!', args: 'Target:string [Potion:string]' },
  swspoiler: { help: 'Generates a random spoiler for Star Wars' },
  tell: { help: 'Sends a tell to the supplied user, with the supplied message.', args: 'Nick:string Message:string' },
  test: { help: 'Test whether you have bot administrator permission.' },
  tonk: { help: 'What is tonk? Tonk is life. For a description of the rules see tonkleaders.' },
  tonkattempts: { help: 'Shows your remaining tonk attempts.' },
  tonkback: { help: 'Move tonk time backward for admin testing.' },
  tonkcode: { help: 'Shows the current tonk verification code.' },
  tonkdestroy: { help: 'Remove users from the tonk scoreboard.', args: 'Nick:string...' },
  tonkforward: { help: 'Move tonk time forward for admin testing.' },
  tonkleaders: { help: 'Shows the tonk leaderboard.' },
  tonkmerge: { help: 'Merge two tonk scoreboard names.', args: 'OldNick:string NewNick:string' },
  tonkout: { help: 'What is tonk? Tonk is life. For a description of the rules see tonkleaders.' },
  tonkpoints: { help: 'Shows tonk points for yourself.' },
  tonkreseteverything: { help: 'Reset the entire tonk scoreboard.' },
  tonksnipe: { help: 'If you are in last place on the tonk scoreboard you can attempt to snipe someone with a green, red, or blue shell. A successful snipe removes a percentage of the difference between your points and theirs, and gives it to you.', args: 'Shell:string [Target:string]' },
  timed: { help: 'Manage timed bans and quiets in this channel.', args: 'SubCommand:string [Nick:string Time:string Reason:string]' },
  unloadplugin: { help: 'Unload a plugin.', args: 'Plugin:string' },
  unignore: { help: 'Remove a user from the global ignore list.', args: 'Nick:string' },
  update: { help: 'Pull the latest bot code and restart if it changed.' },
  weather: { help: 'Returns weather data for the supplied postal code, or place name.', args: 'Location:string' },
  whatislove: { help: 'The answer to the most question' },
  whatami: { help: 'Show your highest bot permission rank.' },
  whopinged: { help: 'Shows you the last pings you had.' },
  warp: { help: 'Go on a vacation! Or end up in a world made out of spaghetti...' },
  xkcd: { help: 'XKCD stuff', args: '[Comic:string]' },
  ytc: { help: 'Enable or disable YouTube video information for this channel.', args: '[State:string]' },
  zap: { help: 'Shocking!', args: '[Target:string Item:string]' }
};

function getHelpMetadata(commandName) {
  return HELP_METADATA[String(commandName || '').trim().toLowerCase()] || null;
}

module.exports = {
  HELP_METADATA,
  getHelpMetadata
};
